spring:
  properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: com.devformed.sickgame.config.CustomPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
com.devformed.sickgame.file-storage.local:
  baseDirectoryPath: /var/storage/sickgame/userUpload/
  tempDirectoryPath: temp/
logging:
  level:
    org:
      springframework:
        security: DEBUG